# Generated by Django 3.2.7 on 2021-11-14 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0004_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rmp_bd_app.campus')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmp_bd_app.professor')),
            ],
        ),
    ]
