# Generated by Django 3.2.7 on 2021-10-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0005_auto_20211006_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='report_flags',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='thumbs_down',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='thumbs_up',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
