# Generated by Django 3.2.7 on 2021-11-14 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0006_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='rmp_bd_app.course')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_id', to='rmp_bd_app.course')),
            ],
            options={
                'verbose_name_plural': 'prerequisites',
            },
        ),
    ]
