# Generated by Django 3.2.7 on 2021-10-27 17:59

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0007_auto_20211024_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
