# Generated by Django 3.2.7 on 2021-11-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0007_auto_20211017_1534'),
        ('rmp_bd_app', '0007_auto_20211019_1347'),
        ('rmp_bd_app', '0008_auto_20211027_1359'),
    ]

    operations = [
    ]
