# Generated by Django 3.2.8 on 2021-10-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0008_alter_student_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.CharField(choices=[('Online', 'Online'), ('Great', 'Great')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='glad_text',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='review',
            name='mad_text',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='review',
            name='sad_text',
            field=models.TextField(max_length=350),
        ),
    ]
