# Generated by Django 3.2.7 on 2021-11-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0008_auto_20211027_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='text',
        ),
        migrations.AddField(
            model_name='tag',
            name='new_tag',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
