# Generated by Django 3.2.7 on 2021-11-15 11:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0009_auto_20211115_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='addTag',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Gives Good Feedback', 'Gives Good Feedback'), ('Lots of Homework', 'Lots of Homework'), ('Accessible Outside of Class', 'Accessible Outside of Class'), ('Attendance Mandatory', 'Attendance Mandatory'), ('Inspirational', 'Inspirational'), ('Test Heavy', 'Test Heavy'), ('Lecture Heavy', 'Lecture Heavy'), ('Extra Credit', 'Extra Credit'), ('Clear Grading Criteria', 'Clear Grading Criteria'), ('Pop Quizzes', 'Pop Quizzes'), ('Caring', 'Caring'), ('Get Ready to Read', 'Get Ready to Read'), ('Respected', 'Respected'), ('Participation Matters', 'Participation Matters'), ('Textbook Required', 'Textbook Required'), ('Graded by a Few Things', 'Graded by a Few Things'), ('Would take again', 'Would take again'), ('Group projects', 'Group projects'), ('Tough Grader', 'Tough Grader'), ('Hilarious', 'Hilarious'), ('Amazing Lectures', 'Amazing Lectures'), ('So Many Papers', 'So Many Papers')], max_length=357, null=True),
        ),
    ]
