# Generated by Django 3.2.8 on 2021-10-28 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0009_auto_20211027_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tags',
        ),
    ]
