# Generated by Django 3.2.7 on 2021-11-14 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0010_professorprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F'), ('Drop/Withdrawal', 'Drop/Withdrawal'), ('Incomplete', 'Incomplete'), ('Not sure yet', 'Not sure yet'), ('Rather not say', 'Rather not say'), ('Audit/No Grade', 'Audit/No Grade')], max_length=15)),
                ('thumbs_up', models.PositiveIntegerField(default=0)),
                ('thumbs_down', models.PositiveIntegerField(default=0)),
                ('report_flags', models.PositiveIntegerField(default=0)),
                ('mad_text', models.CharField(max_length=350)),
                ('sad_text', models.CharField(max_length=350)),
                ('glad_text', models.CharField(max_length=350)),
                ('difficulty_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('professor_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('semester', models.CharField(choices=[('WNTR', 'Winter'), ('SPR', 'Spring'), ('SMR', 'Summer'), ('FALL', 'Fall')], max_length=4)),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021)),
                ('is_textbook', models.BooleanField()),
                ('is_attendance', models.BooleanField()),
                ('is_credit', models.BooleanField()),
                ('is_online', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rmp_bd_app.campus')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmp_bd_app.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmp_bd_app.professor')),
            ],
            options={
                'verbose_name_plural': 'reviews',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmp_bd_app.university'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
