# Generated by Django 3.2.8 on 2021-10-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0010_remove_review_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='report_flags',
        ),
        migrations.RemoveField(
            model_name='review',
            name='thumbs_down',
        ),
        migrations.RemoveField(
            model_name='review',
            name='thumbs_up',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='glad_text',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='review',
            name='mad_text',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='review',
            name='sad_text',
            field=models.CharField(max_length=350),
        ),
    ]
