# Generated by Django 3.2.7 on 2021-11-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0012_review_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rmp_bd_app.university'),
            preserve_default=False,
        ),
    ]
