# Generated by Django 3.2.7 on 2021-12-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0012_review_ip_address'),
    ]

    operations = [
    ]
