# Generated by Django 3.2.7 on 2021-11-14 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0012_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmp_bd_app.review')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmp_bd_app.tag')),
            ],
        ),
    ]
