# Generated by Django 3.2.8 on 2021-10-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0012_remove_review_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='campus',
        ),
    ]
