# Generated by Django 3.2.8 on 2021-10-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0013_remove_review_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='professor',
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.CharField(choices=[(1, 'Yay'), (2, 'Oh')], default='None', max_length=15),
        ),
    ]
