# Generated by Django 3.2.7 on 2021-12-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0013_merge_20211205_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportflag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'reviews'},
        ),
    ]
