# Generated by Django 3.2.7 on 2021-12-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0013_merge_20211205_1918'),
        ('rmp_bd_app', '0013_merge_20211206_2323'),
    ]

    operations = [
    ]
