# Generated by Django 3.2.7 on 2021-12-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0013_course_course_university'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportflag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'reviews'},
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='honorific',
            new_name='title',
        ),
    ]
