# Generated by Django 3.2.7 on 2021-12-06 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0014_auto_20211206_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rmp_bd_app.campus'),
            preserve_default=False,
        ),
    ]
