# Generated by Django 3.2.8 on 2021-10-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0017_alter_review_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MY_CHOICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=154, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='tags',
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(to='rmp_bd_app.MY_CHOICES'),
        ),
    ]
