# Generated by Django 3.2.8 on 2021-10-28 04:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0018_auto_20211027_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tags',
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Yay', 'Yay'), ('Oh', 'Oh')], max_length=15, null=True),
        ),
    ]
