# Generated by Django 3.2.8 on 2021-10-28 04:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0020_alter_review_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Gives Good Feedback', 'Gives Good Feedback'), ('Lots of Homework', 'Lots of Homework'), ('Accessible Outside of Class', 'Accessible Outside of Class'), ('Attendance Mandatory', 'Attendance Mandatory'), ('Inspirational', 'Inspirational'), ('Test Heavy', 'Test Heavy'), ('Lecture Heavy', 'Lecture Heavy'), ('Extra Credit', 'Extra Credit'), ('Clear Grading Criteria', 'Clear Grading Criteria'), ('Pop Quizzes', 'Pop Quizzes'), ('Caring', 'Caring')], max_length=179, null=True),
        ),
    ]
