# Generated by Django 3.2.8 on 2021-10-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0021_alter_review_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_attendance',
        ),
    ]
