# Generated by Django 3.2.8 on 2021-10-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0022_remove_review_is_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='glad_text',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='review',
            name='mad_text',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='review',
            name='sad_text',
            field=models.TextField(max_length=350),
        ),
    ]
