# Generated by Django 3.2.8 on 2021-10-29 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0023_auto_20211028_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rmp_bd_app.professor'),
        ),
    ]
