# Generated by Django 3.2.8 on 2021-10-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0025_auto_20211028_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_attendance',
            field=models.BooleanField(null=True),
        ),
    ]
