# Generated by Django 3.2.8 on 2021-10-29 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmp_bd_app', '0027_auto_20211028_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_attendance',
        ),
    ]
